name: C/C++ Build and Test

on: [push]

jobs:
  test:
    container:
      image: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run
    
  buildcli:
    container:
        image: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make cli
        run: make cli

  buildserver:
    container:
      image: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make server
        run: make server
